name: Jeronimo
version: 0.0.1
description: Jeronimo Mini Game
author: judgetread
authors: [judgetread] 
website: http://emptybukkit.com
main: com.emptybukkit.jeronimo.Jeronimo

commands:
  leave:
    description: Leave a arena
    aliases: [l]
  join:
    description: Leave a arena
    aliases: [j]
  jlist:
    description: Leave a arena
    aliases: [li]